# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false

  config.vm.provider :libvirt do |libvirt|
    libvirt.cpus = "2"
    libvirt.memory = "2048"
    libvirt.autostart = true
  end

  config.vm.define "master" do |v|
    v.vm.box = "generic/ubuntu2004"
    v.vm.hostname = "master"
    v.vm.network "private_network", ip: "10.0.128.2", libvirt__forward_mode: "none", autostart: true
    v.vm.network "forwarded_port", guest: 22, host: 60101
    v.vm.network "forwarded_port", guest: 6443, host: 16443
  end

  config.vm.define "worker1" do |v|
    v.vm.box = "generic/ubuntu2004"
    v.vm.hostname = "worker1"
    v.vm.network "private_network", ip: "10.0.128.3", libvirt__forward_mode: "none", autostart: true
    v.vm.network "forwarded_port", guest: 22, host: 60102
  end

  config.vm.define "worker2" do |v|
    v.vm.box = "generic/ubuntu2004"
    v.vm.hostname = "worker2"
    v.vm.network "private_network", ip: "10.0.128.4", libvirt__forward_mode: "none", autostart: true
    v.vm.network "forwarded_port", guest: 22, host: 60103
  end


  config.vm.provision "ansible" do |ansible|
      ansible.verbose = "v"
      ansible.playbook = "init.yml"
  end

end
