# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false

  config.vm.provider "virtualbox" do |p|
    p.cpus = "2"
    p.memory = "1024"
#    p.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

  config.vm.define "master" do |v|
    v.vm.box = "hashicorp/bionic64"
    v.vm.hostname = "master"
    v.vm.network "private_network", ip: "10.0.128.2"
  end

  config.vm.define "worker1" do |v|
    v.vm.box = "hashicorp/bionic64"
    v.vm.hostname = "worker1"
    v.vm.network "private_network", ip: "10.0.128.3"
  end

  config.vm.define "worker2" do |v|
    v.vm.box = "hashicorp/bionic64"
    v.vm.hostname = "worker2"
    v.vm.network "private_network", ip: "10.0.128.4"
  end

#  config.vm.provision "shell", inline: <<-SHELL
#    echo "HELLO"
#  SHELL

  config.vm.provision "ansible" do |ansible|
      ansible.verbose = "v"
      ansible.playbook = "init.yml"
  end

end
