# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false

  config.vm.provider :libvirt do |libvirt|
    libvirt.cpus = "4"
    libvirt.memory = "1024"
  end

  config.vm.define :iroha1 do |iroha1|
    iroha1.vm.box = "hashicorp/bionic64"
  end

  config.vm.define :iroha2 do |iroha2|
    iroha2.vm.box = "hashicorp/bionic64"
  end

  config.vm.provision "shell", inline: <<-SHELL
    echo "HELLO"
  SHELL

  config.vm.provision "ansible" do |ansible|
      ansible.verbose = "v"
      ansible.playbook = "init.yml"
  end

end
