---
- hosts: all
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
  become: yes
  tasks:
    - name: Delete packages
      apt:
        name: "{{ packages }}"
        state: absent
        update_cache: yes
        autoremove: yes
        purge: yes
      vars:
        packages:
          - "liblxc-common"
          - "liblxc1"
          - "lxcfs"
          - "snapd"

    - name: Install required packages
      apt:
        name: "{{ item }}"
        update_cache: yes
        install_recommends: no
      loop:
        - aptitude
        - python3-pip
        - python3-venv
        - python3-dev
        - python3-setuptools
        - docker.io

    - name: Enable docker
      systemd:
        state: started
        name: docker
        enabled: yes

    - name: Install python packeges
      pip:
        name:
          - docker-compose
