# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false

  config.vm.provider :virtualbox do |p|
    p.cpus = "4"
    p.memory = "1024"
  end

  config.vm.define :vbox_1804_one do |d|
    d.vm.box = "hashicorp/bionic64"
    d.vm.network "forwarded_port", guest: 22, host: 62201, protocol: "tcp", id: 'ssh'
  end

  config.vm.provision :ansible do |ansible|
      ansible.verbose = "v"
      ansible.playbook = "init.yml"
  end

end
