---
- hosts: all
  become: yes
  tasks:
    - name: Install required packages
      apt:
        name: "{{ item }}"
        update_cache: yes
        install_recommends: no
      loop:
        - aptitude
        - python3-pip
        - python3-venv
        - python3-dev
        - python3-setuptools
        - docker.io
    - name: Enable docker
      systemd:
        state: started
        name: docker
        enabled: yes
    - name: Install python packeges
      pip:
        name:
          - docker-compose
          - iroha
